# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true # make the workflow fail on high severity issues
confirm: true #  automatic confirmation of multiple file submissions (equivalent to --yes)

analyze:
  mode: deep
  async: true
  create-group: true
  group-name: "@lukso/lsp-universalprofile-smart-contracts"
  solc: 0.8.7
  remappings:
    - "@erc725/smart-contracts/=node_modules/@erc725/smart-contracts/"
    - "@openzeppelin/=node_modules/@openzeppelin/"
    - "solidity-bytes-utils/=node_modules/solidity-bytes-utils/"
  targets:
    # Standard version
    # ------------------
    - contracts/UniversalProfile.sol
    - contracts/LSP6KeyManager/LSP6KeyManager.sol
    - contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.sol
    - contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault.sol
    - contracts/LSP7DigitalAsset/LSP7DigitalAsset.sol
    - contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.sol
    # Proxy version
    # ------------------
    - contracts/UniversalProfileInit.sol
    - contracts/LSP6KeyManager/LSP6KeyManagerInit.sol
    - contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUPInit.sol
    - contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVaultInit.sol
    - contracts/LSP7DigitalAsset/LSP7DigitalAssetInit.sol
    - contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInit.sol
