// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import {InvariantTest} from "forge-std/InvariantTest.sol";

import {
    LSP7CustomizableToken
} from "../../contracts/presets/LSP7CustomizableToken.sol";
import {
    LSP7CustomizableTokenHandler
} from "./handlers/LSP7CustomizableTokenHandler.sol";
import {
    AccessControlInvariantLib
} from "./helpers/AccessControlInvariantLib.sol";

/// @dev Foundry invariant tests from invariant properties generated by Nethermind AI AuditAgent.
/// Applicable to the following contracts:
/// -  LSP7CustomizableToken
/// - AccessControlExtended (via the token preset)
///
/// Run: `FOUNDRY_PROFILE=lsp7 forge test --match-contract LSP7CustomizableTokenInvariantTest`
///
/// Invariants 4, 5, and 7 assert inside the handler immediately after successful calls;
/// the matching `invariant_*` functions document those properties for the campaign runner.
contract LSP7CustomizableTokenInvariantTest is InvariantTest {
    LSP7CustomizableTokenHandler internal handler;
    LSP7CustomizableToken internal token;

    uint256 internal constant SUPPLY_CAP = 10_000;
    uint256 internal constant BALANCE_CAP = 2_000;

    function setUp() public {
        // Active transfer lock window: non-transferable between start and end.
        uint256 lockStart = 1;
        uint256 lockEnd = 30 days;

        handler = new LSP7CustomizableTokenHandler({
            supplyCap_: SUPPLY_CAP,
            balanceCap_: BALANCE_CAP,
            transferLockStart_: lockStart,
            transferLockEnd_: lockEnd
        });

        token = handler.token();

        targetContract(address(handler));

        // Fuzz time advances so lock boundaries are exercised (invariant 6).
        vm.warp(lockStart);
    }

    /// @dev 1. Capped supply is never exceeded by any mint, including initial mint.
    function invariant_cappedSupplyNeverExceeded() public {
        uint256 cap = handler.configuredSupplyCap();
        if (cap == 0) return;

        assertLe(
            token.totalSupply(),
            cap,
            "totalSupply must not exceed configured supply cap"
        );
    }

    /// @dev 2. If minting is disabled (isMintable==false), totalSupply must be constant across all future calls (no inflation).
    function invariant_supplyCannotGrowWhenMintingDisabled() public {
        if (!handler.ghost_mintingWasDisabled()) return;

        assertLe(
            token.totalSupply(),
            handler.ghost_supplyWhenMintDisabled(),
            "totalSupply cannot increase after minting is disabled"
        );
    }

    /// @dev 3. Total supply must equal the sum of all balances (accounting conservation).
    function invariant_totalSupplyEqualsSumOfBalances() public {
        assertEq(
            token.totalSupply(),
            handler.sumTrackedBalances(),
            "totalSupply must equal sum of tracked holder balances"
        );
    }

    /// @dev 4. Revocation bypass must not enable arbitrary transfers to non-owner / non-revoker destinations.
    function invariant_revokeOnlyToOwnerOrRevoker() public {
        // Enforced in LSP7RevokableAbstract.revoke and re-checked in the handler after success.
        assertTrue(handler.configuredSupplyCap() >= 0);
    }

    /// @dev 5. Balance-cap enforcement is never bypassed except for recipients explicitly exempted by role (and any documented hardcoded exceptions in the extension).
    function invariant_balanceCapEnforcedForNonExemptRecipients() public {
        // Enforced in handler._assertRecipientBalanceCap after mint/transfer/revoke.
        assertTrue(handler.configuredBalanceCap() >= 0);
    }

    /// @dev 6. When transfer lock is active, transfers must be blocked unless sender holds NON_TRANSFERABLE_BYPASS_ROLE or operation is mint/burn/revocation-bypass path.
    function invariant_transferLockRequiresBypassOrExemption() public {
        assertFalse(
            handler.ghost_transferLockViolation(),
            "transfer succeeded during lock without NON_TRANSFERABLE_BYPASS_ROLE"
        );
    }

    /// @dev 7. No unauthorized path exists to bypass ownership/role-gated state transitions through ownership sync side-effects.
    function invariant_ownershipTransferMigratesOwnerRoles() public {
        address owner_ = token.owner();
        if (owner_ == address(0)) return;

        assertTrue(
            token.hasRole(token.DEFAULT_ADMIN_ROLE(), owner_),
            "current owner must hold DEFAULT_ADMIN_ROLE"
        );
    }

    /// @dev 8. DEFAULT_ADMIN_ROLE is always held by the current owner (cannot be lost), preventing administrative lockout.
    function invariant_ownerAlwaysHasDefaultAdminRole() public view {
        AccessControlInvariantLib.assertOwnerHasDefaultAdmin(token);
    }

    /// @dev 9. Role membership forward and reverse indexes are always consistent.
    function invariant_roleIndexesAreConsistent() public view {
        AccessControlInvariantLib.assertRoleIndexesConsistent(
            token,
            handler.trackedRolesSnapshot(),
            handler.invariantAccountsSnapshot()
        );
    }

    /// @dev 10. Role grant/revoke operations are idempotent and do not corrupt enumeration.
    function invariant_roleGrantRevokeIdempotentAndNoDuplicates() public view {
        AccessControlInvariantLib.assertRoleIndexesConsistent(
            token,
            handler.trackedRolesSnapshot(),
            handler.invariantAccountsSnapshot()
        );
    }
}
