# This workflow checks for common grammar and spelling mistake in markdown files.
name: Spellcheck
on: [pull_request]

jobs:
  build:
    name: Check Grammar and Spelling errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ⚙️
        run: npm ci

      - name: Check spelling errors in code snippets 🔍
        uses: codespell-project/actions-codespell@v2
        with:
          path: docs
          check_filenames: true
          ignore_words_list: datas

      - name: Output Spellcheck Results 📝
        uses: actions/upload-artifact@v4
        with:
          name: Spellcheck Output
          path: spellcheck-output.txt
